import type { Metadata } from "next";
import { translate, type Locale } from "@/lib/i18n";
import { Breadcrumbs } from "@/components/Breadcrumbs";

interface Props {
  params: Promise<{ locale: Locale }>;
}

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale } = await params;
  return {
    title: "FAQ - Frequently Asked Questions",
    description: "Find answers to common questions about Social Keyword Generator tools, keyword generation, and SEO optimization.",
    openGraph: {
      title: "FAQ - Frequently Asked Questions",
      description: "Find answers to common questions about Social Keyword Generator tools.",
      images: [{ url: "/og-image.svg", width: 1200, height: 630 }],
    },
  };
}

export default async function FAQPage({ params }: Props) {
  const { locale } = await params;
  const t = (key: string) => translate(locale, key);

  const faqLD = {
    "@context": "https://schema.org",
    "@type": "FAQPage",
    mainEntity: [
      {
        "@type": "Question",
        name: "What is Social Keyword Generator?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Social Keyword Generator is a free AI-powered tool that generates optimized keywords and hashtags for Instagram, TikTok, YouTube, and SEO. Enter any topic and get keyword suggestions instantly.",
        },
      },
      {
        "@type": "Question",
        name: "Is it really free?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Yes! All tools are completely free to use. No sign-up required. We generate revenue through Google AdSense advertisements displayed on the site.",
        },
      },
      {
        "@type": "Question",
        name: "Which platforms do you support?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "We support Instagram hashtag generation, TikTok keywords, YouTube tags, SEO keyword research, and a free keyword generator tool. All optimized for social media.",
        },
      },
      {
        "@type": "Question",
        name: "How does keyword generation work?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Enter a topic or niche, select a tool (Instagram, TikTok, etc.), and our AI generates relevant keywords and hashtags. You can copy results with one click.",
        },
      },
      {
        "@type": "Question",
        name: "How many keywords can I generate?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "There are no limits. Generate keywords as many times as you want across all our tools. No account or payment required.",
        },
      },
      {
        "@type": "Question",
        name: "Are the generated keywords SEO-optimized?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Yes. Our algorithms generate keywords that follow current search trends and platform-specific optimization rules. The SEO tool is specifically designed for search engine optimization.",
        },
      },
      {
        "@type": "Question",
        name: "Do I need to sign up or create an account?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "No. Every tool on SocialKeywordGenerator.com works instantly without any registration. Just open a tool and start generating keywords.",
        },
      },
      {
        "@type": "Question",
        name: "Can I use the generated keywords commercially?",
        acceptedAnswer: {
          "@type": "Answer",
          text: "Absolutely. All keywords and hashtags generated by our tools are yours to use freely — in your posts, videos, marketing campaigns, or any commercial project.",
        },
      },
    ],
  };

  return (
    <div className="container mx-auto px-4 max-w-3xl py-8">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(faqLD) }}
      />
      <Breadcrumbs
        items={[
          {
            label: t("breadcrumbHome"),
            href: locale === "en" ? "/en" : `/${locale}`,
          },
          { label: "FAQ", href: `/${locale}/faq` },
        ]}
      />
      <h1 className="text-3xl font-bold text-gray-900 mb-6">
        Frequently Asked Questions
      </h1>

      <div className="space-y-6">
        {faqLD.mainEntity.map((faq, i) => (
          <details
            key={i}
            className="bg-white rounded-xl border border-gray-100 p-6 group"
          >
            <summary className="font-semibold text-gray-900 cursor-pointer list-none flex justify-between items-center">
              {faq.name}
              <span className="text-gray-400 group-open:rotate-180 transition-transform">
                ▼
              </span>
            </summary>
            <p className="mt-3 text-gray-600 leading-relaxed">
              {faq.acceptedAnswer.text}
            </p>
          </details>
        ))}
      </div>
    </div>
  );
}
