import type { Metadata } from "next";
import { translate } from "@/lib/i18n";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import type { Locale } from "@/lib/i18n";

interface Props { params: Promise<{ locale: Locale }>; }

export async function generateMetadata({ params }: Props): Promise<Metadata> {
  const { locale } = await params;
  return { title: translate(locale, "termsTitle"), description: translate(locale, "termsDesc"), openGraph: { title: translate(locale, "termsTitle"), description: translate(locale, "termsDesc"), images: [{ url: "/og-image.svg", width: 1200, height: 630 }] } };
}

export default async function TermsPage({ params }: Props) {
  const { locale } = await params;
  const t = (key: string) => translate(locale, key);
  const date = "June 4, 2026";

  return (
    <div className="container mx-auto px-4 max-w-3xl py-8">
      <Breadcrumbs items={[
        { label: t("breadcrumbHome"), href: locale === "en" ? "/en" : "/tr" },
        { label: t("terms"), href: `/${locale}/terms` },
      ]} />
      <h1 className="text-3xl font-bold text-gray-900 mb-2">{t("termsTitle")}</h1>
      <p className="text-sm text-gray-400 mb-8">
        {locale === "en" ? `Last updated: ${date}` : `Son güncelleme: ${date}`}
      </p>
      <div className="prose prose-gray max-w-none">
        {locale === "en" ? (
          <>
            <h2>1. Acceptance of Terms</h2>
            <p>By accessing and using SocialKeywordGenerator.com, you accept and agree to be bound by these Terms of Service.</p>
            <h2>2. Service Description</h2>
            <p>We provide free AI-powered social media keyword and hashtag generation tools. All tools are provided &quot;as is&quot; without warranty of any kind.</p>
            <h2>3. User Responsibilities</h2>
            <ul>
              <li>You agree not to misuse our services (automated scraping, excessive API calls)</li>
              <li>You are responsible for the content you generate using our tools</li>
              <li>You agree not to use our tools for illegal or harmful purposes</li>
            </ul>
            <h2>4. Intellectual Property</h2>
            <p>The Social Keyword Generator name, logo, and website content are our intellectual property. Keywords generated by our tools are yours to use freely.</p>
            <h2>5. Limitation of Liability</h2>
            <p>We are not liable for any damages arising from the use of our services. Our tools are provided for informational purposes only.</p>
            <h2>6. Third-Party Links</h2>
            <p>Our site may contain links to third-party websites. We are not responsible for their content or practices.</p>
            <h2>7. Changes to Terms</h2>
            <p>We reserve the right to modify these terms at any time. Continued use after changes constitutes acceptance.</p>
            <h2>8. Contact</h2>
            <p>For questions: <a href="mailto:legal@socialkeywordgenerator.com" className="text-blue-600 hover:underline">legal@socialkeywordgenerator.com</a></p>
          </>
        ) : (
          <>
            <h2>1. Şartların Kabulü</h2>
            <p>SocialKeywordGenerator.com&apos;a erişerek ve kullanarak, bu Kullanım Şartlarını kabul etmiş olursunuz.</p>
            <h2>2. Hizmet Açıklaması</h2>
            <p>Ücretsiz yapay zeka destekli sosyal medya anahtar kelime ve hashtag oluşturma araçları sağlıyoruz. Tüm araçlar &quot;olduğu gibi&quot; ve hiçbir garanti olmaksızın sunulmaktadır.</p>
            <h2>3. Kullanıcı Sorumlulukları</h2>
            <ul>
              <li>Hizmetlerimizi kötüye kullanmamayı kabul edersiniz (otomatik kazıma, aşırı API çağrıları)</li>
              <li>Araçlarımızı kullanarak oluşturduğunuz içerikten siz sorumlusunuz</li>
              <li>Araçlarımızı yasadışı veya zararlı amaçlarla kullanmamayı kabul edersiniz</li>
            </ul>
            <h2>4. Fikri Mülkiyet</h2>
            <p>Social Keyword Generator adı, logosu ve web sitesi içeriği fikri mülkiyetimizdir. Araçlarımız tarafından oluşturulan anahtar kelimeleri özgürce kullanabilirsiniz.</p>
            <h2>5. Sorumluluk Sınırlaması</h2>
            <p>Hizmetlerimizin kullanımından doğabilecek zararlardan sorumlu değiliz. Araçlarımız yalnızca bilgilendirme amaçlıdır.</p>
            <h2>6. Üçüncü Taraf Bağlantıları</h2>
            <p>Sitemiz üçüncü taraf web sitelerine bağlantılar içerebilir. İçeriklerinden veya uygulamalarından sorumlu değiliz.</p>
            <h2>7. Şartlarda Değişiklikler</h2>
            <p>Bu şartları herhangi bir zamanda değiştirme hakkını saklı tutarız. Değişikliklerden sonra kullanıma devam etmek kabul anlamına gelir.</p>
            <h2>8. İletişim</h2>
            <p>Sorular için: <a href="mailto:legal@socialkeywordgenerator.com" className="text-blue-600 hover:underline">legal@socialkeywordgenerator.com</a></p>
          </>
        )}
      </div>
    </div>
  );
}
